# Generated by Django 4.0.4 on 2022-07-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputFile', models.FileField(upload_to='')),
                ('outputFile', models.FileField(blank=True, null=True, upload_to='')),
                ('info', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'PENDING'), ('started', 'STARTED'), ('finished', 'FINISHED'), ('failed', 'FAILED')], default='pending', max_length=10)),
            ],
        ),
    ]
