version: '2'
services:
  app:
    build: .
    env_file:
      - .env
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    depends_on:
      - database

  database:
    image: postgres:latest
    volumes:
      - "psql:/var/lib/psql"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: "name_database"
      POSTGRES_USER: "user_database"
      POSTGRES_PASSWORD: "password_database"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: queue
    ports:
      - 5672:5672
      - 15672:15672

  celery:
    restart: always
    build: .
    env_file:
      - .env
    command: celery -A app worker -l info
    volumes:
      - ".:/app"
    depends_on:
      - app
      - database
      - rabbitmq

volumes:
  psql:
